#+org-modeでの記述方について:

* h1相当
普通の文章
アスタリスクが見出しに相当する。アスタリスクの数がhtmlのhタグの番号に相当する。  
リスト表記でもアスタリスク使えるそうだが、悪さをしそうなので避けたほうが良いでしょう。

* meta + return
見出し(項目？：htmlのh*タグ)が生成できる。

** h2タグ相当

** meta + returnすると
同じ高さの見出し(h*)が生成される

** 見出しでTABを押すと
配下の文章を畳んだり展開してりできる。  
あああ  
  
あああ  
ああああ  
ああああああああああ  
ああああ；ｓｌｋｇｊさ；ｌんゔぁｓろｇ  
あお；ｋまそいｊふぁｓぎｊさお；ｇなｓ  
  
ぎおあｓんふぉしｊがお；’しｇじゃお’しｆｇｊｓ  
あそ；’ふぃｊなそｄふぃｈｇさおｆｇはｓど  

あいｆじゃろｓぎほｆじゃｌｃｋｊ「いｐｈｊゔぁおｒｂｆゔぁ  

お；ぱいなおｓりｇはおｓりｇはおｓｒぎｈじゃｓ’ｒｇあ；おｓｄ  
lafa;lefja;oefihaw;ekfljnaeofuhaw;efliahe;faowiefha;oefha;oefha;alenaofiha;oefhna;oefｖなそいはｒ’ががｊごおあしｇな；ｓりｆはんｒｇはお；ｓりｇはお；  
ｓりｈふぁおｓ；いはおｓ；いｈふぁおｓぢｈふぁそぢｈｆが」  
  
ｌｓｄｋｆｍんさおえ；ｆなふぉゔぁんｒ  
あおｆなｗ；おｒふぃなろ；ぐｊなおるが  
あｆな；ｓｒｌｋんゔぁおｒふいゔぁ’ｒぴｊ

*** C-c C-n, C-c C-p
前後の見出しにジャンプできる。  
見出し配下の文章内にカーソルがある場合にC-c C-p, C-c C-nした場合は最も近い見出しにジャンプする。

*** meta + ↑/↓
見出しにカーソルがある状態なら前後の同じ高さの見出しと上下交換できる。  
文章中ではできない。  
現在の見出しより高い(h1 > h2 > h3...)見出しとは位置交換できない。  
また現在見出しより低い見出しはそれより高い見出しの配下(従属)とみなされ一緒に移動する。

**** sashisuseso
l;faneof'ihoe;cna  
a;nao;rufhawr;oifnas  
aofina;orfuna;orfinua  
a;oenca;ofnaors  
ao;sfnaorgunaiaop'wecoefjqrivberaiou

hige

*** popepope
lkdfnma;sd  
a;dfnao;sdfnas  
a;sdfna;osdfhas

asdfkjvnsdfudha;sor

**** prune
ミキプルーンってあったよね。

*** meta + left/right
見出しの高さを変更できる。  
直接編集したほうが早いきもするが......

** カット&ペースト
見出しと配下の文章を、C-c C-x C-w でカット、 C-c C-x C-y でペースト できる。  
ペーストする位置で見出しの高さが自動で変わってしまうので注意。

** Shift + ←/→
見出しのところで"Shift + ←/→"でタイトルに「TODO」「DONE」をつけることができる。  
コレを使ってToDo管理ができる。

*** ToDoサンプル
- リスト
  * DONE アレする
    SCHEDULED: 2024-11-02
  * TODO コレする
    SCHEDULED: 2024-11-01
  * TODO ソレする
    SCHEDULED: 2024-11-03

* Markdown的な使い方
**強調**  
/イタリック/  
_アンダーライン_  
+打ち消し+  
~inline code~ ~echo "Hello!" > ./hello.sh~  
=そのまま= 文字装飾記号のエスケープか

=[[URL][リンク名]]= [[http://yahoo.co.jp][yahoo]]

C-c C-l でミニバッファでURLと名前(説明)を入力してリンクを挿入することができる。
その際、http(s)以外のURIを選択することも可能。すごいね。
[[https:nfljapan.com][NFLJapan]]
リンク状態になっている場所にカーソルを当て  **C-c C-o** でブラウザで開くことができる。

おまけ：
[[[[https://www.mhatta.org/wp/2018/08/23/org-mode-101-3/]]][LaTeXについて]]

- リスト
- 項目２
- 項目３
  1. saburisuto
  2. サブリスト２
  3. サブリスト３
  4. サブリスト4
- 項目４
- 項目５
- 項目６
  1. プラスでも入れ子にできる
  2. other2
  3. other3

**C-c -** するたびにリスト記号をまとめて変更できる。  
-/+/1. とリスト記号を使った場合、改行で自動インデントされるが **リストとして認識されないので注意！！！**  
リスト構造を維持した改行をしたい場合は、 **meta + return** だ。  
**meta + ↑/↓** で見出し同様にリストの順番を入れ替えることができる。  
**C-c C-c** で番号振り直ししてくれる。

*** チェックボックスもできるよ

meta + returnでチェックボックス付きリストを生成できる。

- ルーティン作業 [2/5]
  - [ ] メールチェック
  - [ ] Chatwork確認
  - [X] Web巡回
  - [X] 動画ルーティン
  - [ ] 課題読書

リストのタイトル行に[0/0]をつけるとチェック行の個数をカウントしてくれる。__
[0%]の場合は達成率になる。
チェックはそそのリストの上で **C-c C-c** をするとチェックが付く。


| header1    | header2 | header3 |
| あーなるほど | うひ     | おふ     |
| なんか      | じゃない | どれどれ |
| 内容１      | 内容２   | 内容３   |
| ううん      | おおん   | ああん   |
|            |         |         |

途中で間違ってスペースを入れてしまうとそのスペースが消せなくなるんだが......  
TABを押すと最大文字数に合わせて整形してくれる。これは便利！  
あとTABでカラム移動が出来、最終行最終カラムの場合は次の行を自動生成してくれる。  
めちゃ便利。


**** 定義リスト
- ラーメン :: 醤油、塩、味噌など
- カレー :: アルー・ゴビー、バラック・サブジ、ラジマなど

よくわからない......

*** 他

=ハイフン5つで水平線(-----)=
-----

[fn:: インライン脚注]

**** 引用とか
#+BEGIN_QUOTE
サイは投げられた。 -- カエサル
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(defun xor (a b)
     "Exclusive or."
     (if a (not b) b))
#+END_SRC


* Export
C-c C-e で書き出しができるらしい。  
h -> h でカレントにhtmlを排出してくれる。  
別のバッファにオプションや設定の画面が展開されるが、正直使い方が分からん。


# コメント
